const produtosMae = [
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },
    { nome: "Bolo Especial da Mãe", preco: "99,99", un: "/un" },


];

const contentorMae = document.getElementById('lista-mae');

produtosMae.forEach(produto => {
    contentorMae.innerHTML += `
        <div class="produto-item">
            <span class="produto-nome">• ${produto.nome}</span>
            <span class="produto-preco">${produto.preco}€ <small>${produto.un}</small></span>
        </div>
    `;
});